# Generated by Django 3.2.16 on 2024-10-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generals', '0002_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='comment',
            field=models.CharField(default='', max_length=50),
        ),
    ]
